env:
  es2021: true
  node: true
extends:
  - plugin:jest/recommended
  - plugin:jest/style
  - eslint:recommended
  - next/core-web-vitals
  - plugin:testing-library/react

parser: "@typescript-eslint/parser"
parserOptions:
  project: 
  - './tsconfig.json'
  - './tsconfig.jest.json'

  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - jest
  - "@typescript-eslint"

rules:
  indent: 0
  "@typescript-eslint/no-explicit-any": 1
  "@typescript-eslint/no-unused-vars": 1
  '@typescript-eslint/explicit-module-boundary-types': 0
  linebreak-style: 0
  "import/no-extraneous-dependencies": 1
  quotes: 0
  semi: 0
